# Generated by Django 5.0.4 on 2025-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_panier_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='gains_retires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
