# Generated by Django 5.2 on 2025-04-13 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profil_gains_retires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('filleul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mon_parrain', to=settings.AUTH_USER_MODEL)),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_filleuls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
