# Generated by Django 5.2 on 2025-04-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parrainage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
