# Generated by Django 5.2 on 2025-10-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mon_code',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profil',
            name='mon_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
