# Generated by Django 5.2 on 2025-10-18 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser_mon_code_profil_mon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mon_code',
        ),
        migrations.AddField(
            model_name='profil',
            name='mes_filleuls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profil',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parrains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profil',
            name='parrain_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
