# Generated by Django 5.2 on 2025-10-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gains',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='parrain',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='solde',
        ),
    ]
