# Generated by Django 5.2 on 2025-10-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_customuser_gains_remove_customuser_parrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gains',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
