# Generated by Django 5.2 on 2025-10-19 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_gains_customuser_nom_customuser_parrain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='mes_filleuls',
        ),
        migrations.AddField(
            model_name='profil',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gains_retires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profil',
            name='mon_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profil',
            name='parrain_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
