# Generated by Django 5.2 on 2025-10-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_profil_mes_filleuls_profil_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='mon_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
