# Generated by Django 5.2 on 2025-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profil_mon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='mon_code',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
    ]
