# Generated by Django 5.2 on 2025-12-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profil_mon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='parrain',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_parrainage',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL),
        ),
    ]
