# Generated by Django 5.2 on 2025-12-01 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_profil_parrain_customuser_code_parrainage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='code_parrainage',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
