# Generated by Django 5.2 on 2026-02-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_profil_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleul', to=settings.AUTH_USER_MODEL),
        ),
    ]
