# Generated by Django 5.2 on 2026-02-26 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_profil_avatar_alter_customuser_parrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='panier',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
    ]
