# Generated by Django 5.2 on 2026-03-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='parrain',
        ),
    ]
