# Generated by Django 5.2 on 2026-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_profil_parrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
