# Generated by Django 5.2 on 2026-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_customuser_nom_remove_customuser_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='telephone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
